# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Task.create(content: 'content 1', status: 'status 1')
Task.create(content: 'content 2', status: 'status 2')
Task.create(content: 'content 3', status: 'status 3')
Task.create(content: 'content 4', status: 'status 4')
Task.create(content: 'content 5', status: 'status 5')
Task.create(content: 'content 6', status: 'status 6')
Task.create(content: 'content 7', status: 'status 7')
Task.create(content: 'content 8', status: 'status 8')
Task.create(content: 'content 9', status: 'status 9')
Task.create(content: 'content 10', status: 'status 10')
Task.create(content: 'content 11', status: 'status 11')
Task.create(content: 'content 12', status: 'status 12')
Task.create(content: 'content 13', status: 'status 13')
Task.create(content: 'content 14', status: 'status 14')
Task.create(content: 'content 15', status: 'status 15')
Task.create(content: 'content 16', status: 'status 16')
Task.create(content: 'content 17', status: 'status 17')
Task.create(content: 'content 18', status: 'status 18')
Task.create(content: 'content 19', status: 'status 19')
Task.create(content: 'content 20', status: 'status 20')
Task.create(content: 'content 21', status: 'status 21')
Task.create(content: 'content 22', status: 'status 22')
Task.create(content: 'content 23', status: 'status 23')
Task.create(content: 'content 24', status: 'status 24')
Task.create(content: 'content 25', status: 'status 25')
Task.create(content: 'content 26', status: 'status 26')
Task.create(content: 'content 27', status: 'status 27')
Task.create(content: 'content 28', status: 'status 28')
Task.create(content: 'content 29', status: 'status 29')
Task.create(content: 'content 30', status: 'status 30')
